### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by burstw0w** [victorsouzaleal/instagram-direct-url#21]
I think there is something wrong with the way API gives back json, as JSON is not parsed correctly anymore. Might look into it over the weekend, but i also think you should take a look.

Errors i get:

```
SyntaxError: Unexpected token 'I', "Invalid ur"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5477:19)
    at successSteps (node:internal/deps/undici/undici:5459:27)
    at fullyReadBody (node:internal/deps/undici/undici:4378:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:5468:7)
    at async /root/noviIHI/node_modules/instagram-url-direct/src/index.js:30:26
```
    
And:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at packageData (node:internal/deps/undici/undici:6370:23)
    at specConsumeBody (node:internal/deps/undici/undici:6348:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\burstw0w\test\instagram-direct-url\src\index.js:30:26
  
```

So it's both from my PC and the server.

**Comment by victorsouzaleal** [comment]
If you can send an example link where this is happening.

**Comment by burstw0w** [comment]
https://www.instagram.com/reel/DBbJNcrSDd4/

This one, but i got some errors with the test URL that you currently have in the code.

**Comment by burstw0w** [comment]
I do have to say that sometimes it works, sometimes it doesnt.

**Comment by victorsouzaleal** [comment]
Got it, I had the same problem, maybe there is an internal request limit now

**Comment by burstw0w** [comment]
If you can share how you look for valid API's to use, i could try and fix this using another site.

**Comment by victorsouzaleal** [comment]
check if it's working on new version

**Comment by burstw0w** [comment]
Seems to be working. I will close the issue, as the api was changed, but will open a new one if i find any issues with the current one. Thanks for a quick fix
